### ISSUE TITLE
Initial On/Off state

### ISSUE THREAD

**Issue by meeDamian** [Serchinastico/CoolSwitch#2]
Would be great if setting `.setChecked(Boolean checked)` in java or `android:checked="true|false"` in xml on `com.serchinastico.coolswitch.CoolSwitch` element worked properly - setting backgrounds, and stuff.

**Comment by Serchinastico** [comment]
I fixed the `setChecked` calls but I'm afraid the xml part has to be done manually (showing or hiding the linked views depending on the application state). 
The reason is that I need to know if these views are inflated or not in order to change their visibility and given that I'm not restricting these views relationship I don't have anything to subscribe to know their state. There are two options:
1. Add a new method to let the switch know when it's safe to update the views visibility.
2. Rethink the design of the switch to have control over the inflation of the linked views.

I don't like the first option at all as it's messing with responsibilities. On the other hand, the second option sounds good to me but I'm afraid I don't have the time neither the motivation :(

Thanks for the report!

**Comment by meeDamian** [comment]
If it's possible to manually set it from java, I don't think it's required to spend time to make xml work - everyone interested can just manually set it on init.
